### ISSUE TITLE
÷%÷ key malfunctioning. 

### ISSUE THREAD

**Issue by Sudhee-bsp** [ishanbagchi/calculator#13]
As we know these operators actively cannot function on digits. 

ex:- **31÷%** must produce result like **0.31**

Either it should change the prior operator from **31÷** to **31%** 
OR must produce the result like above.

**Comment by NidhiTater** [comment]
Assign this to me please

**Comment by ishanbagchi** [comment]
Ya sure but it is not counted for the hacktoberfest, is it ok @NidhiTater.

**Comment by Sudhee-bsp** [comment]
Nope @ishanbagchi, actually even this PR can be counted (even though you haven't labelled it as hacktober). This issue is likely fixing bug, so no worries, if you made a PR for this issue, it will get counted for sure.✌
@NidhiTater , You can work on it.

**Comment by NidhiTater** [comment]
Thanks! I have started working on it. 
Also, to make it eligible for hacktoberfest , please add the label "hacktoberfest-accepted" to my PR .
